/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Ticket.booking;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class App {
    public static void main(String[] args) {

//        List<Integer>  l = Arrays.asList(1,2,3,4,5,6,7,8,9);
//        List<Integer> l1 = l.stream().filter(i -> i%2 == 0).map(i -> i*i).toList();
//
//        //output
//        System.out.println(l1);
//
//        l.stream().map(e-> e*2).collect(Collectors.toList());

    }
}
